plugins {
	id "idea"
	id "eclipse"
	id "net.neoforged.moddev.legacyforge" version "2.0.74"
	id "me.modmuss50.mod-publish-plugin" version "0.8.3"
	id "dev.ithundxr.silk" version "0.11.15"
	id "org.jetbrains.gradle.plugin.idea-ext" version "1.1.8"
}

apply from: "./gradle/java.gradle"

boolean dev = System.getenv('RELEASE') == null || System.getenv('RELEASE').equals('false')
ext.buildNumber = System.getenv('BUILD_NUMBER')
String gitHash = "\"${calculateGitHash() + (hasUnstaged() ? "-modified" : "")}\""

base {
	archivesName = "robotics-${artifact_minecraft_version}"
	group = 'com.workert.robotics'
	version = mod_version + (dev && buildNumber != null ? "-${buildNumber}" : '')
}

mixin {
	add sourceSets.main, 'robotics.refmap.json'
	config 'robotics.mixins.json'
}

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

idea {
	module {
		downloadJavadoc = true
		downloadSources = true
	}
}

legacyForge {
	version = "$minecraft_version-$forge_version"

	if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
		accessTransformers.from "src/main/resources/META-INF/accesstransformer.cfg"
	}

	parchment {
		minecraftVersion = minecraft_version
		mappingsVersion = parchment_version
	}

	mods {
		robotics {
			sourceSet sourceSets.main
		}
	}

	runs {
		configureEach {
			systemProperty 'forge.logging.markers', ''
			systemProperty 'forge.logging.console.level', 'info'
			jvmArguments = ["-XX:+IgnoreUnrecognizedVMOptions", "-XX:+AllowEnhancedClassRedefinition"]

			systemProperty 'mixin.debug.export', 'true'
			systemProperty 'mixin.debug.verbose', 'true'

			programArgument '-mixin.config=robotics.mixins.json'
			programArgument '-mixin.config=ponder.mixins.json'
		}

		client {
			client()
			gameDirectory = project.file('run')
		}

		server {
			server()
			gameDirectory = project.file('run/server')
		}

		data {
			data()
			gameDirectory = project.file('run')
			systemProperty 'forge.logging.markers', 'REGISTRIES,REGISTRYDUMP'
			systemProperty 'forge.logging.console.level', 'debug'
			programArguments.addAll("--mod", mod_id as String, "--all", "--output", file("src/generated/resources/").getAbsolutePath(), "--existing", file("src/main/resources").getAbsolutePath())
		}

		gameTestServer {
			type = "gameTestServer"
			gameDirectory = project.file('run/gametest')
		}
	}
}

repositories {
	maven { url = "https://maven.createmod.net" }
	maven { url = "https://maven.tterrag.com" }
	maven { url = "https://www.cursemaven.com" }
	maven { url = "https://api.modrinth.com/maven" }
	maven { url = "https://maven.blamejared.com" }
	maven { url = "https://harleyoconnor.com/maven" }
	maven { url = "https://maven.theillusivec4.top/" }
	maven { url = "https://maven.squiddev.cc" }
	maven { url = "https://maven.saps.dev/releases" }
	maven { url = "https://maven.architectury.dev" }
	maven {
		url = "https://jm.gserv.me/repository/maven-public"
		content {
			includeGroup "info.journeymap"
			includeGroup "mysticdrew"
		}
	}
	mavenCentral()
	mavenLocal()
	flatDir {
		dirs "libs"
	}
}

dependencies {
	modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:all")
	modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
	implementation("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}")
	modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
	modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
	modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
	compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
	modImplementation("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
	modCompileOnly("top.theillusivec4.curios:curios-forge:${curios_version}+${minecraft_version}:api")
	modRuntimeOnly("top.theillusivec4.curios:curios-forge:${curios_version}+${minecraft_version}")
	modImplementation("curse.maven:journeymap-32274:5457831")

	if (!Boolean.getBoolean('idea.sync.active')) {
		annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
	}
}

sourceSets.main {
	resources {
		srcDir 'src/generated/resources'
		exclude '.cache/'
	}
}

processResources {
	def buildProps = project.properties.clone()
	buildProps.put('file', [jarVersion: project.version])
	filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
		expand buildProps
	}
}

compileJava {
	options.compilerArgs = ['-Xdiags:verbose']
}

jar {
	from('LICENSE') {
		rename { "${it}_${archivesBaseName}" }
	}
	manifest.attributes([
			"MixinConfigs": "robotics.mixins.json",
			"Git-Hash"    : gitHash
	])
}

tasks.named("sourcesJar") {
	manifest.attributes([
			"Git-Hash": gitHash
	])
}

String calculateGitHash() {
	try {
		def output = providers.exec {
			commandLine("git", "rev-parse", "HEAD")
		}
		return output.standardOutput.asText.get().trim()
	} catch (Throwable ignored) {
		return "unknown"
	}
}

boolean hasUnstaged() {
	try {
		def output = providers.exec {
			commandLine("git", "status", "--porcelain")
		}
		String result = output.standardOutput.asText.get().replace("/M gradlew(\\.bat)?/", "").trim()
		if (!result.isEmpty())
			println("Found stageable results:\n ${result}\n")
		return !result.isEmpty()
	} catch (Throwable ignored) {
		return false
	}
}

///////////////////////////////////////
// 👇 FIX para evitar fallo con 1.0.13
///////////////////////////////////////
configurations.all {
	resolutionStrategy.eachDependency { details ->
		if (details.requested.group == "net.neoforged" &&
				details.requested.name == "neoform-runtime") {
			details.useVersion("1.0.12")
			details.because("La 1.0.13 está rota en el repositorio Maven")
		}
	}
}
